version: "3"
services:
    database:
        image: mongo
        restart: always
        ports:
            - "27017"
    rabbitmq:
        image: rabbitmq:3.7-management
        ports:
            - "4370"
            - "5672"
            - "15672"
    apiapplication:
        build: ./
        ports:
            - 80:3000
        depends_on:
            - database
            - rabbitmq
        environment: 
            - MONGO_URL=mongodb://database
            - AMQP_URL=rabbitmq
            - NODE_ENV=production
